In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. **EDA**.

# **A. Check basic information again**

In [42]:
print(df.shape)
df.info()
df.describe()

(3025, 22)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3025 entries, 0 to 3024
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Post_ID                       3025 non-null   object
 1   Timestamp                     3025 non-null   object
 2   Platform                      3025 non-null   object
 3   Content_Type                  3025 non-null   object
 4   Category                      3025 non-null   object
 5   Likes                         3025 non-null   int64
 6   Comments                      3025 non-null   int64
 7   Shares                        3025 non-null   int64
 8   Views                         3025 non-null   int64
 9   Saves                         3025 non-null   int64
 10  Follower_Count                3025 non-null   int64
 11  Engagement_Rate               3025 non-null   float64
 12  Hour_of_Day                   3025 non-null   int64
 13  Day_of_Week                   3025 non-null   object
 14  Hashtag_Count                 3025 non-null   int64
 15  Content_Length                3025 non-null   int64
 16  Sentiment                     3025 non-null   object
 17  Influencer_Tier               3025 non-null   object
 18  Has_Media                     3025 non-null   bool
 19  Is_Verified                   3025 non-null   bool
 20  Flag_Engagement_Above_Views   3025 non-null   bool
 21  Flag_Engagement_Rate_Outlier  3025 non-null   bool
dtypes: bool(4), float64(1), int64(9), object(8)
memory usage: 437.3+ KB

,Likes,Comments,Shares,Views,Saves,Follower_Count,Engagement_Rate,Hour_of_Day,Hashtag_Count,Content_Length
count,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000,3025.00000,3025.000000,3025.000000,3025.000000,3025.000000
mean,9910.899174,422.275041,851.301818,86901.163306,742.953058,247475.62281,16.258522,11.510083,14.532893,657.365950
std,11944.962957,462.769564,1210.354518,121208.993566,683.684526,144998.87731,90.214362,6.919223,8.668669,548.272956
min,35.000000,3.000000,2.000000,551.000000,8.000000,543.00000,0.060000,0.000000,0.000000,15.000000
25%,2914.000000,137.000000,138.000000,19576.000000,296.000000,122702.00000,1.420000,5.000000,7.000000,236.000000
50%,5739.000000,273.000000,280.000000,38651.000000,558.000000,242641.00000,3.010000,12.000000,15.000000,465.000000
75%,9047.000000,435.000000,870.000000,72320.000000,868.000000,373219.00000,8.520000,18.000000,22.000000,1021.000000
max,49949.000000,1999.000000,4997.000000,497812.000000,2999.000000,499815.00000,3510.460000,23.000000,29.000000,1999.000000

# **B. Analyze the platforms**

In [43]:
df["Platform"].value_counts()

Platform
Instagram    1283
Facebook      984
TikTok        758
Name: count, dtype: int64

# **C. Analyze engagement**

In [44]:
df[["Likes", "Comments", "Shares", "Views", "Saves", "Engagement_Rate"]].describe()

,Likes,Comments,Shares,Views,Saves,Engagement_Rate
count,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000
mean,9910.899174,422.275041,851.301818,86901.163306,742.953058,16.258522
std,11944.962957,462.769564,1210.354518,121208.993566,683.684526,90.214362
min,35.000000,3.000000,2.000000,551.000000,8.000000,0.060000
25%,2914.000000,137.000000,138.000000,19576.000000,296.000000,1.420000
50%,5739.000000,273.000000,280.000000,38651.000000,558.000000,3.010000
75%,9047.000000,435.000000,870.000000,72320.000000,868.000000,8.520000
max,49949.000000,1999.000000,4997.000000,497812.000000,2999.000000,3510.460000

# **D. Analyze content type**

In [45]:
df.groupby("Content_Type")["Engagement_Rate"].mean().sort_values(ascending=False)

Content_Type
Stitch      45.382664
Duet        41.630242
Video       22.608184
Reel        11.674739
Post        10.323583
Carousel     8.376246
Photo        6.283531
Story        5.924190
Live         5.494310
Name: Engagement_Rate, dtype: float64

# **E. Analyze posting time**

In [46]:
df.groupby("Hour_of_Day")["Engagement_Rate"].mean()

Hour_of_Day
0     22.401951
1     20.636642
2     16.671607
3      7.553083
4     14.815606
5     12.126202
6     10.157385
7     33.415304
8     39.347705
9     15.274297
10    12.391450
11    11.486579
12     6.817840
13    16.899612
14    13.709098
15    12.318696
16    18.177815
17    10.998992
18    23.188496
19    11.014355
20    28.488344
21    10.316812
22     8.070153
23    16.141068
Name: Engagement_Rate, dtype: float64

# **F. Analyze hashtags**

In [47]:
df.groupby("Hashtag_Count")["Engagement_Rate"].mean()

Hashtag_Count
0      9.980841
1     14.164706
2      7.757528
3     29.803100
4      5.602000
5     11.223097
6     27.166449
7     45.532909
8     12.890588
9     14.946796
10    14.368273
11    34.398557
12     8.632267
13    13.358750
14    17.317426
15    10.639802
16     9.237374
17     9.638989
18    13.383131
19    12.321414
20    11.618073
21    11.029145
22    13.738700
23    16.325714
24    12.769515
25    18.290948
26    21.449588
27     7.617000
28    23.953818
29    22.879444
Name: Engagement_Rate, dtype: float64

In [36]:
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/monkeydlundy/socail-media-dataset/filtered_tiktok_facebook_instagram (2).csv

In [34]:
df = pd.read_csv('/kaggle/input/datasets/monkeydlundy/socail-media-dataset/filtered_tiktok_facebook_instagram (2).csv')

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

Rows: 3025
Columns: 22

,Post_ID,Timestamp,Platform,Content_Type,Category,Likes,Comments,Shares,Views,Saves,...,Hour_of_Day,Day_of_Week,Hashtag_Count,Content_Length,Sentiment,Influencer_Tier,Has_Media,Is_Verified,Flag_Engagement_Above_Views,Flag_Engagement_Rate_Outlier
0,POST_04552,2024-01-01 01:42:00,Instagram,Carousel,Business,8287,247,51,29502,20,...,1,Monday,16,985,Positive,Macro,True,False,False,False
1,POST_00210,2024-01-01 09:18:00,Instagram,Carousel,Food,1527,191,7,5460,359,...,9,Monday,27,79,Positive,Macro,True,True,False,False
2,POST_01548,2024-01-01 10:58:00,Facebook,Video,Sports,535,178,433,68246,740,...,10,Monday,17,554,Neutral,Macro,True,False,False,False
3,POST_01350,2024-01-01 13:12:00,Instagram,Photo,Fitness,9706,35,118,25782,611,...,13,Monday,5,1136,Positive,Mid-tier,True,False,False,True
4,POST_04605,2024-01-02 20:22:00,TikTok,Video,Travel,18977,966,2147,8088,2235,...,20,Tuesday,5,369,Negative,Macro,False,False,True,False

In [4]:
print(df.columns.tolist())

['post_id', 'source', 'timestamp', 'day_of_week', 'hour_of_day', 'platform', 'user_id', 'location', 'language', 'text_content', 'content_type', 'content_length', 'hashtags', 'hashtag_count', 'mentions', 'keywords', 'topic_category', 'brand_name', 'product_name', 'campaign_name', 'campaign_phase', 'sentiment', 'sentiment_score', 'emotion_type', 'toxicity_score', 'likes', 'comments', 'shares', 'saves', 'views', 'engagement_rate', 'follower_count', 'influencer_tier', 'has_media', 'is_verified', 'user_past_sentiment_avg', 'user_engagement_growth', 'buzz_change_rate']

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 38 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   post_id                  17000 non-null  object
 1   source                   17000 non-null  object
 2   timestamp                17000 non-null  object
 3   day_of_week              17000 non-null  object
 4   hour_of_day              5000 non-null   float64
 5   platform                 17000 non-null  object
 6   user_id                  12000 non-null  object
 7   location                 12000 non-null  object
 8   language                 12000 non-null  object
 9   text_content             12000 non-null  object
 10  content_type             5000 non-null   object
 11  content_length           5000 non-null   float64
 12  hashtags                 12000 non-null  object
 13  hashtag_count            5000 non-null   float64
 14  mentions                 8059 non-null   object
 15  keywords                 12000 non-null  object
 16  topic_category           17000 non-null  object
 17  brand_name               12000 non-null  object
 18  product_name             12000 non-null  object
 19  campaign_name            12000 non-null  object
 20  campaign_phase           12000 non-null  object
 21  sentiment                17000 non-null  object
 22  sentiment_score          12000 non-null  float64
 23  emotion_type             12000 non-null  object
 24  toxicity_score           12000 non-null  float64
 25  likes                    17000 non-null  int64
 26  comments                 17000 non-null  int64
 27  shares                   17000 non-null  int64
 28  saves                    5000 non-null   float64
 29  views                    17000 non-null  int64
 30  engagement_rate          17000 non-null  float64
 31  follower_count           5000 non-null   float64
 32  influencer_tier          5000 non-null   object
 33  has_media                5000 non-null   object
 34  is_verified              5000 non-null   object
 35  user_past_sentiment_avg  12000 non-null  float64
 36  user_engagement_growth   12000 non-null  float64
 37  buzz_change_rate         12000 non-null  float64
dtypes: float64(11), int64(4), object(23)
memory usage: 4.9+ MB

In [6]:
print(df.isnull().sum())

post_id                        0
source                         0
timestamp                      0
day_of_week                    0
hour_of_day                12000
platform                       0
user_id                     5000
location                    5000
language                    5000
text_content                5000
content_type               12000
content_length             12000
hashtags                    5000
hashtag_count              12000
mentions                    8941
keywords                    5000
topic_category                 0
brand_name                  5000
product_name                5000
campaign_name               5000
campaign_phase              5000
sentiment                      0
sentiment_score             5000
emotion_type                5000
toxicity_score              5000
likes                          0
comments                       0
shares                         0
saves                      12000
views                          0
engagement_rate                0
follower_count             12000
influencer_tier            12000
has_media                  12000
is_verified                12000
user_past_sentiment_avg     5000
user_engagement_growth      5000
buzz_change_rate            5000
dtype: int64

In [37]:
print(df['performance'].value_counts())

KeyError: 'performance'

In [39]:
leakage_columns = [
    'likes',
    'comments',
    'shares',
    'saves',
    'impressions',
    'reach',
    'engagement_rate'
]

df = df.drop(
    columns=[col for col in leakage_columns if col in df.columns],
    errors='ignore'
)

In [40]:
features = [
    'follower_count',
    'media_type',
    'content_category',
    'caption_length',
    'hashtag_count',
    'post_hour',
    'day_of_week',
    'traffic_source',
    'cta_indicator'
]

features = [col for col in features if col in df.columns]

print("Features being used:")
print(features)

Features being used:
[]

In [41]:
X = df[features]

y = df['performance']

KeyError: 'performance'

In [15]:
print(y.value_counts())

NameError: name 'y' is not defined

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training:", X_train.shape)
print("Testing:", X_test.shape)

NameError: name 'y' is not defined

In [17]:
numeric_features = X.select_dtypes(
    include=['int64', 'float64']
).columns.tolist()

categorical_features = X.select_dtypes(
    include=['object', 'category', 'bool']
).columns.tolist()

print("Numeric:", numeric_features)
print("Categorical:", categorical_features)

Numeric: ['follower_count', 'hashtag_count']
Categorical: ['day_of_week']

In [25]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            'passthrough',
            numeric_features
        ),
        (
            'cat',
            OneHotEncoder(
                handle_unknown='ignore'
            ),
            categorical_features
        )
    ]
)

In [27]:
model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight='balanced',
    n_jobs=-1
)

In [28]:
pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', model)
    ]
)

In [29]:
pipeline.fit(X_train, y_train)

print("Model training completed!")

NameError: name 'X_train' is not defined

In [30]:
y_pred = pipeline.predict(X_test)

print(y_pred[:20])

NameError: name 'X_test' is not defined

In [31]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", round(accuracy * 100, 2), "%")

NameError: name 'y_test' is not defined

In [32]:
print(
    classification_report(
        y_test,
        y_pred
    )
)

NameError: name 'y_test' is not defined

In [33]:
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(7, 5))

plt.imshow(cm)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.xticks(
    range(len(pipeline.classes_)),
    pipeline.classes_,
    rotation=45
)

plt.yticks(
    range(len(pipeline.classes_)),
    pipeline.classes_
)

plt.colorbar()

plt.tight_layout()
plt.show()

NameError: name 'y_test' is not defined

In [ ]:
new_post = pd.DataFrame({
    'follower_count': [10000],
    'media_type': ['Video'],
    'content_category': ['Fashion'],
    'caption_length': [80],
    'hashtag_count': [5],
    'post_hour': [19],
    'day_of_week': ['Friday'],
    'traffic_source': ['Explore'],
    'cta_indicator': [1]
})

In [ ]:
prediction = pipeline.predict(new_post)

print("Predicted Performance:", prediction[0])

In [ ]:
probabilities = pipeline.predict_proba(new_post)

for class_name, probability in zip(
    pipeline.classes_,
    probabilities[0]
):
    print(
        class_name,
        ":",
        round(probability * 100, 2),
        "%"
    )

In [ ]:
import joblib

joblib.dump(
    pipeline,
    'digital_content_engagement_model.pkl'
)

print("Model saved!")

In [ ]:
import joblib

model = joblib.load(
    'digital_content_engagement_model.pkl'
)

In [ ]:
##### prediction = model.predict(new_post)

print(prediction)